spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: password
    hikari:
      transaction-isolation: 4  # postgres default is 2 (read committed), 4 is (repeatable read)