server:
  port: ${random.int(8000,9000)}

spring:
  jpa:
    open-in-view: false
    show-sql: true
  profiles:
    default: yugabyte

logging:
  level:
    #org.postgresql: DEBUG
    #com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG
    net.javacrumbs.shedlock: DEBUG
    org.springframework.transaction.interceptor: TRACE